version: '3.3'
services:
  db:
    image: mysql:8.0.12
    env_file: ./container/db/.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
